services:
  frontend:
    image: lycohana/todos-frontend:latest
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    image: lycohana/todos-backend:latest
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=todos_db
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - app-network
    depends_on:
      - database
    volumes:
      - todo_details:/app/backend/todo-details

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=todos_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:
  todo_details:

networks:
  app-network:
    driver: bridge
